// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/test.proto

package com.github.sisyphsu.nakedata.proto;

public interface MultiMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.sisyphsu.nakedata.proto.MultiMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg1 = 1;</code>
   */
  java.lang.String getMsg1();
  /**
   * <code>string msg1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsg1Bytes();

  /**
   * <code>string msg2 = 2;</code>
   */
  java.lang.String getMsg2();
  /**
   * <code>string msg2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsg2Bytes();

  /**
   * <code>string msg3 = 3;</code>
   */
  java.lang.String getMsg3();
  /**
   * <code>string msg3 = 3;</code>
   */
  com.google.protobuf.ByteString
      getMsg3Bytes();

  /**
   * <code>string msg4 = 4;</code>
   */
  java.lang.String getMsg4();
  /**
   * <code>string msg4 = 4;</code>
   */
  com.google.protobuf.ByteString
      getMsg4Bytes();

  /**
   * <code>string msg5 = 5;</code>
   */
  java.lang.String getMsg5();
  /**
   * <code>string msg5 = 5;</code>
   */
  com.google.protobuf.ByteString
      getMsg5Bytes();
}
