// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/test.proto

package com.github.sisyphsu.nakedata.proto;

public interface SingleMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.sisyphsu.nakedata.proto.SingleMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
