// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/test.proto

package com.github.sisyphsu.nakedata.proto;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_sisyphsu_nakedata_proto_UserDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_sisyphsu_nakedata_proto_UserDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_sisyphsu_nakedata_proto_SingleMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_sisyphsu_nakedata_proto_SingleMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_sisyphsu_nakedata_proto_MultiMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_sisyphsu_nakedata_proto_MultiMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032resources/proto/test.proto\022\"com.github" +
      ".sisyphsu.nakedata.proto\"r\n\nUserDetail\022\n" +
      "\n\002id\030\001 \001(\003\022\013\n\003age\030\002 \001(\005\022\020\n\010nickname\030\003 \001(" +
      "\t\022\021\n\tavatarUrl\030\004 \001(\t\022\022\n\ncreateTime\030\n \001(\003" +
      "\022\022\n\nupdateTime\030\013 \001(\003\"\030\n\tSingleMsg\022\013\n\003msg" +
      "\030\001 \001(\t\"P\n\010MultiMsg\022\014\n\004msg1\030\001 \001(\t\022\014\n\004msg2" +
      "\030\002 \001(\t\022\014\n\004msg3\030\003 \001(\t\022\014\n\004msg4\030\004 \001(\t\022\014\n\004ms" +
      "g5\030\005 \001(\tB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_sisyphsu_nakedata_proto_UserDetail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_sisyphsu_nakedata_proto_UserDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_sisyphsu_nakedata_proto_UserDetail_descriptor,
        new java.lang.String[] { "Id", "Age", "Nickname", "AvatarUrl", "CreateTime", "UpdateTime", });
    internal_static_com_github_sisyphsu_nakedata_proto_SingleMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_sisyphsu_nakedata_proto_SingleMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_sisyphsu_nakedata_proto_SingleMsg_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_com_github_sisyphsu_nakedata_proto_MultiMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_github_sisyphsu_nakedata_proto_MultiMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_sisyphsu_nakedata_proto_MultiMsg_descriptor,
        new java.lang.String[] { "Msg1", "Msg2", "Msg3", "Msg4", "Msg5", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
