// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/proto/message.proto

package com.github.sisyphsu.canoe.model;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.sisyphsu.canoe.model.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>bool enable = 2;</code>
     * @return The enable.
     */
    boolean getEnable();

    /**
     * <code>float score1 = 3;</code>
     * @return The score1.
     */
    float getScore1();

    /**
     * <code>double score2 = 4;</code>
     * @return The score2.
     */
    double getScore2();

    /**
     * <code>string text = 5;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>string text = 5;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
     */
    java.util.List<com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver> 
        getReceiversList();
    /**
     * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
     */
    com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver getReceivers(int index);
    /**
     * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
     */
    int getReceiversCount();
    /**
     * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
     */
    java.util.List<? extends com.github.sisyphsu.canoe.model.MessageOuterClass.ReceiverOrBuilder> 
        getReceiversOrBuilderList();
    /**
     * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
     */
    com.github.sisyphsu.canoe.model.MessageOuterClass.ReceiverOrBuilder getReceiversOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.github.sisyphsu.canoe.model.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.sisyphsu.canoe.model.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      text_ = "";
      receivers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              enable_ = input.readBool();
              break;
            }
            case 29: {

              score1_ = input.readFloat();
              break;
            }
            case 33: {

              score2_ = input.readDouble();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            case 48: {

              timestamp_ = input.readInt64();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                receivers_ = new java.util.ArrayList<com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver>();
                mutable_bitField0_ |= 0x00000001;
              }
              receivers_.add(
                  input.readMessage(com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          receivers_ = java.util.Collections.unmodifiableList(receivers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.sisyphsu.canoe.model.MessageOuterClass.internal_static_com_github_sisyphsu_canoe_model_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.sisyphsu.canoe.model.MessageOuterClass.internal_static_com_github_sisyphsu_canoe_model_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.sisyphsu.canoe.model.MessageOuterClass.Message.class, com.github.sisyphsu.canoe.model.MessageOuterClass.Message.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int ENABLE_FIELD_NUMBER = 2;
    private boolean enable_;
    /**
     * <code>bool enable = 2;</code>
     * @return The enable.
     */
    public boolean getEnable() {
      return enable_;
    }

    public static final int SCORE1_FIELD_NUMBER = 3;
    private float score1_;
    /**
     * <code>float score1 = 3;</code>
     * @return The score1.
     */
    public float getScore1() {
      return score1_;
    }

    public static final int SCORE2_FIELD_NUMBER = 4;
    private double score2_;
    /**
     * <code>double score2 = 4;</code>
     * @return The score2.
     */
    public double getScore2() {
      return score2_;
    }

    public static final int TEXT_FIELD_NUMBER = 5;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 5;</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 5;</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int RECEIVERS_FIELD_NUMBER = 7;
    private java.util.List<com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver> receivers_;
    /**
     * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
     */
    public java.util.List<com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver> getReceiversList() {
      return receivers_;
    }
    /**
     * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
     */
    public java.util.List<? extends com.github.sisyphsu.canoe.model.MessageOuterClass.ReceiverOrBuilder> 
        getReceiversOrBuilderList() {
      return receivers_;
    }
    /**
     * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
     */
    public int getReceiversCount() {
      return receivers_.size();
    }
    /**
     * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
     */
    public com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver getReceivers(int index) {
      return receivers_.get(index);
    }
    /**
     * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
     */
    public com.github.sisyphsu.canoe.model.MessageOuterClass.ReceiverOrBuilder getReceiversOrBuilder(
        int index) {
      return receivers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (enable_ != false) {
        output.writeBool(2, enable_);
      }
      if (score1_ != 0F) {
        output.writeFloat(3, score1_);
      }
      if (score2_ != 0D) {
        output.writeDouble(4, score2_);
      }
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, text_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(6, timestamp_);
      }
      for (int i = 0; i < receivers_.size(); i++) {
        output.writeMessage(7, receivers_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (enable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, enable_);
      }
      if (score1_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, score1_);
      }
      if (score2_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, score2_);
      }
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, text_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timestamp_);
      }
      for (int i = 0; i < receivers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, receivers_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.sisyphsu.canoe.model.MessageOuterClass.Message)) {
        return super.equals(obj);
      }
      com.github.sisyphsu.canoe.model.MessageOuterClass.Message other = (com.github.sisyphsu.canoe.model.MessageOuterClass.Message) obj;

      if (getId()
          != other.getId()) return false;
      if (getEnable()
          != other.getEnable()) return false;
      if (java.lang.Float.floatToIntBits(getScore1())
          != java.lang.Float.floatToIntBits(
              other.getScore1())) return false;
      if (java.lang.Double.doubleToLongBits(getScore2())
          != java.lang.Double.doubleToLongBits(
              other.getScore2())) return false;
      if (!getText()
          .equals(other.getText())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getReceiversList()
          .equals(other.getReceiversList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + ENABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnable());
      hash = (37 * hash) + SCORE1_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getScore1());
      hash = (37 * hash) + SCORE2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getScore2()));
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      if (getReceiversCount() > 0) {
        hash = (37 * hash) + RECEIVERS_FIELD_NUMBER;
        hash = (53 * hash) + getReceiversList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.sisyphsu.canoe.model.MessageOuterClass.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.sisyphsu.canoe.model.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.sisyphsu.canoe.model.Message)
        com.github.sisyphsu.canoe.model.MessageOuterClass.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.sisyphsu.canoe.model.MessageOuterClass.internal_static_com_github_sisyphsu_canoe_model_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.sisyphsu.canoe.model.MessageOuterClass.internal_static_com_github_sisyphsu_canoe_model_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.sisyphsu.canoe.model.MessageOuterClass.Message.class, com.github.sisyphsu.canoe.model.MessageOuterClass.Message.Builder.class);
      }

      // Construct using com.github.sisyphsu.canoe.model.MessageOuterClass.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getReceiversFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        enable_ = false;

        score1_ = 0F;

        score2_ = 0D;

        text_ = "";

        timestamp_ = 0L;

        if (receiversBuilder_ == null) {
          receivers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          receiversBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.sisyphsu.canoe.model.MessageOuterClass.internal_static_com_github_sisyphsu_canoe_model_Message_descriptor;
      }

      @java.lang.Override
      public com.github.sisyphsu.canoe.model.MessageOuterClass.Message getDefaultInstanceForType() {
        return com.github.sisyphsu.canoe.model.MessageOuterClass.Message.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.sisyphsu.canoe.model.MessageOuterClass.Message build() {
        com.github.sisyphsu.canoe.model.MessageOuterClass.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.sisyphsu.canoe.model.MessageOuterClass.Message buildPartial() {
        com.github.sisyphsu.canoe.model.MessageOuterClass.Message result = new com.github.sisyphsu.canoe.model.MessageOuterClass.Message(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.enable_ = enable_;
        result.score1_ = score1_;
        result.score2_ = score2_;
        result.text_ = text_;
        result.timestamp_ = timestamp_;
        if (receiversBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            receivers_ = java.util.Collections.unmodifiableList(receivers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.receivers_ = receivers_;
        } else {
          result.receivers_ = receiversBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.sisyphsu.canoe.model.MessageOuterClass.Message) {
          return mergeFrom((com.github.sisyphsu.canoe.model.MessageOuterClass.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.sisyphsu.canoe.model.MessageOuterClass.Message other) {
        if (other == com.github.sisyphsu.canoe.model.MessageOuterClass.Message.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getEnable() != false) {
          setEnable(other.getEnable());
        }
        if (other.getScore1() != 0F) {
          setScore1(other.getScore1());
        }
        if (other.getScore2() != 0D) {
          setScore2(other.getScore2());
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (receiversBuilder_ == null) {
          if (!other.receivers_.isEmpty()) {
            if (receivers_.isEmpty()) {
              receivers_ = other.receivers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureReceiversIsMutable();
              receivers_.addAll(other.receivers_);
            }
            onChanged();
          }
        } else {
          if (!other.receivers_.isEmpty()) {
            if (receiversBuilder_.isEmpty()) {
              receiversBuilder_.dispose();
              receiversBuilder_ = null;
              receivers_ = other.receivers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              receiversBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getReceiversFieldBuilder() : null;
            } else {
              receiversBuilder_.addAllMessages(other.receivers_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.sisyphsu.canoe.model.MessageOuterClass.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.sisyphsu.canoe.model.MessageOuterClass.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private boolean enable_ ;
      /**
       * <code>bool enable = 2;</code>
       * @return The enable.
       */
      public boolean getEnable() {
        return enable_;
      }
      /**
       * <code>bool enable = 2;</code>
       * @param value The enable to set.
       * @return This builder for chaining.
       */
      public Builder setEnable(boolean value) {
        
        enable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool enable = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnable() {
        
        enable_ = false;
        onChanged();
        return this;
      }

      private float score1_ ;
      /**
       * <code>float score1 = 3;</code>
       * @return The score1.
       */
      public float getScore1() {
        return score1_;
      }
      /**
       * <code>float score1 = 3;</code>
       * @param value The score1 to set.
       * @return This builder for chaining.
       */
      public Builder setScore1(float value) {
        
        score1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float score1 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore1() {
        
        score1_ = 0F;
        onChanged();
        return this;
      }

      private double score2_ ;
      /**
       * <code>double score2 = 4;</code>
       * @return The score2.
       */
      public double getScore2() {
        return score2_;
      }
      /**
       * <code>double score2 = 4;</code>
       * @param value The score2 to set.
       * @return This builder for chaining.
       */
      public Builder setScore2(double value) {
        
        score2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double score2 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore2() {
        
        score2_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 5;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 5;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 5;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 5;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 6;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 6;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver> receivers_ =
        java.util.Collections.emptyList();
      private void ensureReceiversIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          receivers_ = new java.util.ArrayList<com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver>(receivers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver, com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.Builder, com.github.sisyphsu.canoe.model.MessageOuterClass.ReceiverOrBuilder> receiversBuilder_;

      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public java.util.List<com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver> getReceiversList() {
        if (receiversBuilder_ == null) {
          return java.util.Collections.unmodifiableList(receivers_);
        } else {
          return receiversBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public int getReceiversCount() {
        if (receiversBuilder_ == null) {
          return receivers_.size();
        } else {
          return receiversBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver getReceivers(int index) {
        if (receiversBuilder_ == null) {
          return receivers_.get(index);
        } else {
          return receiversBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public Builder setReceivers(
          int index, com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver value) {
        if (receiversBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReceiversIsMutable();
          receivers_.set(index, value);
          onChanged();
        } else {
          receiversBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public Builder setReceivers(
          int index, com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.Builder builderForValue) {
        if (receiversBuilder_ == null) {
          ensureReceiversIsMutable();
          receivers_.set(index, builderForValue.build());
          onChanged();
        } else {
          receiversBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public Builder addReceivers(com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver value) {
        if (receiversBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReceiversIsMutable();
          receivers_.add(value);
          onChanged();
        } else {
          receiversBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public Builder addReceivers(
          int index, com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver value) {
        if (receiversBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReceiversIsMutable();
          receivers_.add(index, value);
          onChanged();
        } else {
          receiversBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public Builder addReceivers(
          com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.Builder builderForValue) {
        if (receiversBuilder_ == null) {
          ensureReceiversIsMutable();
          receivers_.add(builderForValue.build());
          onChanged();
        } else {
          receiversBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public Builder addReceivers(
          int index, com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.Builder builderForValue) {
        if (receiversBuilder_ == null) {
          ensureReceiversIsMutable();
          receivers_.add(index, builderForValue.build());
          onChanged();
        } else {
          receiversBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public Builder addAllReceivers(
          java.lang.Iterable<? extends com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver> values) {
        if (receiversBuilder_ == null) {
          ensureReceiversIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, receivers_);
          onChanged();
        } else {
          receiversBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public Builder clearReceivers() {
        if (receiversBuilder_ == null) {
          receivers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          receiversBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public Builder removeReceivers(int index) {
        if (receiversBuilder_ == null) {
          ensureReceiversIsMutable();
          receivers_.remove(index);
          onChanged();
        } else {
          receiversBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.Builder getReceiversBuilder(
          int index) {
        return getReceiversFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public com.github.sisyphsu.canoe.model.MessageOuterClass.ReceiverOrBuilder getReceiversOrBuilder(
          int index) {
        if (receiversBuilder_ == null) {
          return receivers_.get(index);  } else {
          return receiversBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public java.util.List<? extends com.github.sisyphsu.canoe.model.MessageOuterClass.ReceiverOrBuilder> 
           getReceiversOrBuilderList() {
        if (receiversBuilder_ != null) {
          return receiversBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(receivers_);
        }
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.Builder addReceiversBuilder() {
        return getReceiversFieldBuilder().addBuilder(
            com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.getDefaultInstance());
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.Builder addReceiversBuilder(
          int index) {
        return getReceiversFieldBuilder().addBuilder(
            index, com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.getDefaultInstance());
      }
      /**
       * <code>repeated .com.github.sisyphsu.canoe.model.Receiver receivers = 7;</code>
       */
      public java.util.List<com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.Builder> 
           getReceiversBuilderList() {
        return getReceiversFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver, com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.Builder, com.github.sisyphsu.canoe.model.MessageOuterClass.ReceiverOrBuilder> 
          getReceiversFieldBuilder() {
        if (receiversBuilder_ == null) {
          receiversBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver, com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.Builder, com.github.sisyphsu.canoe.model.MessageOuterClass.ReceiverOrBuilder>(
                  receivers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          receivers_ = null;
        }
        return receiversBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.sisyphsu.canoe.model.Message)
    }

    // @@protoc_insertion_point(class_scope:com.github.sisyphsu.canoe.model.Message)
    private static final com.github.sisyphsu.canoe.model.MessageOuterClass.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.sisyphsu.canoe.model.MessageOuterClass.Message();
    }

    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.sisyphsu.canoe.model.MessageOuterClass.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReceiverOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.sisyphsu.canoe.model.Receiver)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 userId = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>string iconUrl = 2;</code>
     * @return The iconUrl.
     */
    java.lang.String getIconUrl();
    /**
     * <code>string iconUrl = 2;</code>
     * @return The bytes for iconUrl.
     */
    com.google.protobuf.ByteString
        getIconUrlBytes();

    /**
     * <code>string remark = 3;</code>
     * @return The remark.
     */
    java.lang.String getRemark();
    /**
     * <code>string remark = 3;</code>
     * @return The bytes for remark.
     */
    com.google.protobuf.ByteString
        getRemarkBytes();

    /**
     * <code>int32 followNum = 4;</code>
     * @return The followNum.
     */
    int getFollowNum();

    /**
     * <code>int32 fanNum = 5;</code>
     * @return The fanNum.
     */
    int getFanNum();

    /**
     * <code>int64 createTime = 6;</code>
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <code>int64 updateTime = 7;</code>
     * @return The updateTime.
     */
    long getUpdateTime();
  }
  /**
   * Protobuf type {@code com.github.sisyphsu.canoe.model.Receiver}
   */
  public  static final class Receiver extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.sisyphsu.canoe.model.Receiver)
      ReceiverOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Receiver.newBuilder() to construct.
    private Receiver(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Receiver() {
      iconUrl_ = "";
      remark_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Receiver();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Receiver(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              iconUrl_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              remark_ = s;
              break;
            }
            case 32: {

              followNum_ = input.readInt32();
              break;
            }
            case 40: {

              fanNum_ = input.readInt32();
              break;
            }
            case 48: {

              createTime_ = input.readInt64();
              break;
            }
            case 56: {

              updateTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.sisyphsu.canoe.model.MessageOuterClass.internal_static_com_github_sisyphsu_canoe_model_Receiver_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.sisyphsu.canoe.model.MessageOuterClass.internal_static_com_github_sisyphsu_canoe_model_Receiver_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.class, com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>int32 userId = 1;</code>
     * @return The userId.
     */
    public int getUserId() {
      return userId_;
    }

    public static final int ICONURL_FIELD_NUMBER = 2;
    private volatile java.lang.Object iconUrl_;
    /**
     * <code>string iconUrl = 2;</code>
     * @return The iconUrl.
     */
    public java.lang.String getIconUrl() {
      java.lang.Object ref = iconUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iconUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string iconUrl = 2;</code>
     * @return The bytes for iconUrl.
     */
    public com.google.protobuf.ByteString
        getIconUrlBytes() {
      java.lang.Object ref = iconUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iconUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMARK_FIELD_NUMBER = 3;
    private volatile java.lang.Object remark_;
    /**
     * <code>string remark = 3;</code>
     * @return The remark.
     */
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      }
    }
    /**
     * <code>string remark = 3;</code>
     * @return The bytes for remark.
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FOLLOWNUM_FIELD_NUMBER = 4;
    private int followNum_;
    /**
     * <code>int32 followNum = 4;</code>
     * @return The followNum.
     */
    public int getFollowNum() {
      return followNum_;
    }

    public static final int FANNUM_FIELD_NUMBER = 5;
    private int fanNum_;
    /**
     * <code>int32 fanNum = 5;</code>
     * @return The fanNum.
     */
    public int getFanNum() {
      return fanNum_;
    }

    public static final int CREATETIME_FIELD_NUMBER = 6;
    private long createTime_;
    /**
     * <code>int64 createTime = 6;</code>
     * @return The createTime.
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int UPDATETIME_FIELD_NUMBER = 7;
    private long updateTime_;
    /**
     * <code>int64 updateTime = 7;</code>
     * @return The updateTime.
     */
    public long getUpdateTime() {
      return updateTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      if (!getIconUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, iconUrl_);
      }
      if (!getRemarkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, remark_);
      }
      if (followNum_ != 0) {
        output.writeInt32(4, followNum_);
      }
      if (fanNum_ != 0) {
        output.writeInt32(5, fanNum_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(6, createTime_);
      }
      if (updateTime_ != 0L) {
        output.writeInt64(7, updateTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (!getIconUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, iconUrl_);
      }
      if (!getRemarkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, remark_);
      }
      if (followNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, followNum_);
      }
      if (fanNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, fanNum_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createTime_);
      }
      if (updateTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, updateTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver)) {
        return super.equals(obj);
      }
      com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver other = (com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (!getIconUrl()
          .equals(other.getIconUrl())) return false;
      if (!getRemark()
          .equals(other.getRemark())) return false;
      if (getFollowNum()
          != other.getFollowNum()) return false;
      if (getFanNum()
          != other.getFanNum()) return false;
      if (getCreateTime()
          != other.getCreateTime()) return false;
      if (getUpdateTime()
          != other.getUpdateTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + ICONURL_FIELD_NUMBER;
      hash = (53 * hash) + getIconUrl().hashCode();
      hash = (37 * hash) + REMARK_FIELD_NUMBER;
      hash = (53 * hash) + getRemark().hashCode();
      hash = (37 * hash) + FOLLOWNUM_FIELD_NUMBER;
      hash = (53 * hash) + getFollowNum();
      hash = (37 * hash) + FANNUM_FIELD_NUMBER;
      hash = (53 * hash) + getFanNum();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.sisyphsu.canoe.model.Receiver}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.sisyphsu.canoe.model.Receiver)
        com.github.sisyphsu.canoe.model.MessageOuterClass.ReceiverOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.sisyphsu.canoe.model.MessageOuterClass.internal_static_com_github_sisyphsu_canoe_model_Receiver_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.sisyphsu.canoe.model.MessageOuterClass.internal_static_com_github_sisyphsu_canoe_model_Receiver_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.class, com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.Builder.class);
      }

      // Construct using com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        iconUrl_ = "";

        remark_ = "";

        followNum_ = 0;

        fanNum_ = 0;

        createTime_ = 0L;

        updateTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.sisyphsu.canoe.model.MessageOuterClass.internal_static_com_github_sisyphsu_canoe_model_Receiver_descriptor;
      }

      @java.lang.Override
      public com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver getDefaultInstanceForType() {
        return com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver build() {
        com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver buildPartial() {
        com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver result = new com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver(this);
        result.userId_ = userId_;
        result.iconUrl_ = iconUrl_;
        result.remark_ = remark_;
        result.followNum_ = followNum_;
        result.fanNum_ = fanNum_;
        result.createTime_ = createTime_;
        result.updateTime_ = updateTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver) {
          return mergeFrom((com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver other) {
        if (other == com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getIconUrl().isEmpty()) {
          iconUrl_ = other.iconUrl_;
          onChanged();
        }
        if (!other.getRemark().isEmpty()) {
          remark_ = other.remark_;
          onChanged();
        }
        if (other.getFollowNum() != 0) {
          setFollowNum(other.getFollowNum());
        }
        if (other.getFanNum() != 0) {
          setFanNum(other.getFanNum());
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.getUpdateTime() != 0L) {
          setUpdateTime(other.getUpdateTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 userId = 1;</code>
       * @return The userId.
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object iconUrl_ = "";
      /**
       * <code>string iconUrl = 2;</code>
       * @return The iconUrl.
       */
      public java.lang.String getIconUrl() {
        java.lang.Object ref = iconUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iconUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string iconUrl = 2;</code>
       * @return The bytes for iconUrl.
       */
      public com.google.protobuf.ByteString
          getIconUrlBytes() {
        java.lang.Object ref = iconUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iconUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string iconUrl = 2;</code>
       * @param value The iconUrl to set.
       * @return This builder for chaining.
       */
      public Builder setIconUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iconUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string iconUrl = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIconUrl() {
        
        iconUrl_ = getDefaultInstance().getIconUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string iconUrl = 2;</code>
       * @param value The bytes for iconUrl to set.
       * @return This builder for chaining.
       */
      public Builder setIconUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iconUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object remark_ = "";
      /**
       * <code>string remark = 3;</code>
       * @return The remark.
       */
      public java.lang.String getRemark() {
        java.lang.Object ref = remark_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remark_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string remark = 3;</code>
       * @return The bytes for remark.
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        java.lang.Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string remark = 3;</code>
       * @param value The remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemark(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string remark = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemark() {
        
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <code>string remark = 3;</code>
       * @param value The bytes for remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remark_ = value;
        onChanged();
        return this;
      }

      private int followNum_ ;
      /**
       * <code>int32 followNum = 4;</code>
       * @return The followNum.
       */
      public int getFollowNum() {
        return followNum_;
      }
      /**
       * <code>int32 followNum = 4;</code>
       * @param value The followNum to set.
       * @return This builder for chaining.
       */
      public Builder setFollowNum(int value) {
        
        followNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 followNum = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFollowNum() {
        
        followNum_ = 0;
        onChanged();
        return this;
      }

      private int fanNum_ ;
      /**
       * <code>int32 fanNum = 5;</code>
       * @return The fanNum.
       */
      public int getFanNum() {
        return fanNum_;
      }
      /**
       * <code>int32 fanNum = 5;</code>
       * @param value The fanNum to set.
       * @return This builder for chaining.
       */
      public Builder setFanNum(int value) {
        
        fanNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 fanNum = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFanNum() {
        
        fanNum_ = 0;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>int64 createTime = 6;</code>
       * @return The createTime.
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>int64 createTime = 6;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 createTime = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private long updateTime_ ;
      /**
       * <code>int64 updateTime = 7;</code>
       * @return The updateTime.
       */
      public long getUpdateTime() {
        return updateTime_;
      }
      /**
       * <code>int64 updateTime = 7;</code>
       * @param value The updateTime to set.
       * @return This builder for chaining.
       */
      public Builder setUpdateTime(long value) {
        
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 updateTime = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearUpdateTime() {
        
        updateTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.sisyphsu.canoe.model.Receiver)
    }

    // @@protoc_insertion_point(class_scope:com.github.sisyphsu.canoe.model.Receiver)
    private static final com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver();
    }

    public static com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Receiver>
        PARSER = new com.google.protobuf.AbstractParser<Receiver>() {
      @java.lang.Override
      public Receiver parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Receiver(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Receiver> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Receiver> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.sisyphsu.canoe.model.MessageOuterClass.Receiver getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_sisyphsu_canoe_model_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_sisyphsu_canoe_model_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_sisyphsu_canoe_model_Receiver_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_sisyphsu_canoe_model_Receiver_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&src/test/resources/proto/message.proto" +
      "\022\037com.github.sisyphsu.canoe.model\"\244\001\n\007Me" +
      "ssage\022\n\n\002id\030\001 \001(\005\022\016\n\006enable\030\002 \001(\010\022\016\n\006sco" +
      "re1\030\003 \001(\002\022\016\n\006score2\030\004 \001(\001\022\014\n\004text\030\005 \001(\t\022" +
      "\021\n\ttimestamp\030\006 \001(\003\022<\n\treceivers\030\007 \003(\0132)." +
      "com.github.sisyphsu.canoe.model.Receiver" +
      "\"\206\001\n\010Receiver\022\016\n\006userId\030\001 \001(\005\022\017\n\007iconUrl" +
      "\030\002 \001(\t\022\016\n\006remark\030\003 \001(\t\022\021\n\tfollowNum\030\004 \001(" +
      "\005\022\016\n\006fanNum\030\005 \001(\005\022\022\n\ncreateTime\030\006 \001(\003\022\022\n" +
      "\nupdateTime\030\007 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_sisyphsu_canoe_model_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_sisyphsu_canoe_model_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_sisyphsu_canoe_model_Message_descriptor,
        new java.lang.String[] { "Id", "Enable", "Score1", "Score2", "Text", "Timestamp", "Receivers", });
    internal_static_com_github_sisyphsu_canoe_model_Receiver_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_sisyphsu_canoe_model_Receiver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_sisyphsu_canoe_model_Receiver_descriptor,
        new java.lang.String[] { "UserId", "IconUrl", "Remark", "FollowNum", "FanNum", "CreateTime", "UpdateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
